addons:
  sonarcloud:
    organization: "julenalzas"
    token: "8dffff1f1b144819b5443c956600f008dd577fec"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar sonar:sonar 